################################################# 
# Pipeline para compilar la solución en DEV     #
# antes de hacer pull request a la rama master  #
#################################################

trigger: none

pr:
  branches:
    include: [dev]

stages:
  ###################################
  ## Fase de Build
  ###################################
  - stage: 'Build_Pull_Request'
    displayName: 'Building PR Phase'
    jobs:
    - job:
      displayName: 'Build Job'
      pool: 
        vmImage: 'ubuntu-latest'
      
      variables:
        - group: 'Recetas VG'
        - name: Solution
          value: '**/*.sln'
        - name: TestProject
          value: '**/*[Tt]est/*.csproj'

      steps:
      - checkout: self
        clean: true
        
      - task: DotNetCoreCLI@2
        displayName: 'Restore Packages'
        inputs:
          command: restore
          projects: $(Solution)
        
      - task: DotNetCoreCLI@2
        displayName: Build
        inputs:
          projects: $(Solution)
          arguments: '--configuration $(BuildConfiguration)'
      
      - script: 'echo ''##vso[task.setvariable variable=CONNECTIONSTRINGS__TABLESTORAGECS]$(TableStorageCS)'''
        displayName: 'Set Environment Variables'
        
      - task: DotNetCoreCLI@2
        displayName: Test
        inputs:
          command: test
          projects: $(TestProject)
          arguments: '--configuration $(BuildConfiguration)'

